[build-system]
requires = [
    "setuptools>=61",
    "wheel",
    "scikit-build>=0.17.6",
    "cmake>=3.18",
    "torch==2.0.0",
    "nanobind>=1.1.0",
    "ninja; platform_system!='Windows'"
]


build-backend = "setuptools.build_meta"
