[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "scikit-build>=0.16.7",
    "cmake>=3.18",
    "nanobind>=1.1.0",
    "torch==2.0.0+cpu",
    "ninja; platform_system!='Windows'"
]

build-backend = "setuptools.build_meta"
